// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Customer defines model for Customer.
type Customer struct {
	ContactEmail  *string             `json:"contactEmail,omitempty"`
	ContactPerson *string             `json:"contactPerson,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	Name          *string             `json:"name,omitempty"`
	ProjectId     *openapi_types.UUID `json:"projectId,omitempty"`
	UpdatedAt     *time.Time          `json:"updatedAt,omitempty"`
}

// Error defines model for Error.
type Error struct {
	ErrorCode string `json:"ErrorCode"`
	Message   string `json:"Message"`
	Error     string `json:"error"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Customer  *string             `json:"customer,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	UpdatedAt *time.Time          `json:"updatedAt,omitempty"`
}

// ProjectProgress defines model for ProjectProgress.
type ProjectProgress struct {
	ContactEmail *string             `json:"contactEmail,omitempty"`
	CreatedAt    *time.Time          `json:"createdAt,omitempty"`
	CustomerName *string             `json:"customerName,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Message      *string             `json:"message,omitempty"`
	Name         *string             `json:"name,omitempty"`
	ProjectId    *openapi_types.UUID `json:"projectId,omitempty"`
	StartTime    *time.Time          `json:"startTime,omitempty"`
	SubStageId   *openapi_types.UUID `json:"subStageId,omitempty"`
	UpdatedAt    *time.Time          `json:"updatedAt,omitempty"`
}

// Stage defines model for Stage.
type Stage struct {
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
	ProjectId   *openapi_types.UUID `json:"projectId,omitempty"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitempty"`
}

// SubStage defines model for SubStage.
type SubStage struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Duration  *int                `json:"duration,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	StageId   *openapi_types.UUID `json:"stageId,omitempty"`
	StartTime *time.Time          `json:"startTime,omitempty"`
	UpdatedAt *time.Time          `json:"updatedAt,omitempty"`
}

// BatchCreateSubStagesJSONBody defines parameters for BatchCreateSubStages.
type BatchCreateSubStagesJSONBody = []SubStage

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = Customer

// CreateProjectProgressJSONRequestBody defines body for CreateProjectProgress for application/json ContentType.
type CreateProjectProgressJSONRequestBody = ProjectProgress

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = Project

// CreateStageJSONRequestBody defines body for CreateStage for application/json ContentType.
type CreateStageJSONRequestBody = Stage

// UpdateStageJSONRequestBody defines body for UpdateStage for application/json ContentType.
type UpdateStageJSONRequestBody = Stage

// BatchCreateSubStagesJSONRequestBody defines body for BatchCreateSubStages for application/json ContentType.
type BatchCreateSubStagesJSONRequestBody = BatchCreateSubStagesJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new customer
	// (POST /customers)
	CreateCustomer(c *fiber.Ctx) error
	// Create a new project progress record
	// (POST /projectProgress)
	CreateProjectProgress(c *fiber.Ctx) error
	// Get project progress by ID
	// (GET /projectProgress/{progressId})
	GetProjectProgressByID(c *fiber.Ctx, progressId openapi_types.UUID) error
	// Update an existing project progress record
	// (PUT /projectProgress/{progressId})
	UpdateProjectProgress(c *fiber.Ctx, progressId openapi_types.UUID) error
	// Get all projects
	// (GET /projects)
	GetAllProjects(c *fiber.Ctx) error
	// Create a new project
	// (POST /projects)
	CreateProject(c *fiber.Ctx) error
	// Get a project by ID
	// (GET /projects/{projectId})
	GetProjectByID(c *fiber.Ctx, projectId openapi_types.UUID) error
	// Create a new stage
	// (POST /stages)
	CreateStage(c *fiber.Ctx) error
	// Get a stage by ID
	// (GET /stages/{stageId})
	GetStageByID(c *fiber.Ctx, stageId openapi_types.UUID) error
	// Update an existing stage
	// (PUT /stages/{stageId})
	UpdateStage(c *fiber.Ctx, stageId openapi_types.UUID) error
	// Batch create substages
	// (POST /subStages/batch)
	BatchCreateSubStages(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(c *fiber.Ctx) error {

	return siw.Handler.CreateCustomer(c)
}

// CreateProjectProgress operation middleware
func (siw *ServerInterfaceWrapper) CreateProjectProgress(c *fiber.Ctx) error {

	return siw.Handler.CreateProjectProgress(c)
}

// GetProjectProgressByID operation middleware
func (siw *ServerInterfaceWrapper) GetProjectProgressByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "progressId" -------------
	var progressId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "progressId", c.Params("progressId"), &progressId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter progressId: %w", err).Error())
	}

	return siw.Handler.GetProjectProgressByID(c, progressId)
}

// UpdateProjectProgress operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectProgress(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "progressId" -------------
	var progressId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "progressId", c.Params("progressId"), &progressId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter progressId: %w", err).Error())
	}

	return siw.Handler.UpdateProjectProgress(c, progressId)
}

// GetAllProjects operation middleware
func (siw *ServerInterfaceWrapper) GetAllProjects(c *fiber.Ctx) error {

	return siw.Handler.GetAllProjects(c)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(c *fiber.Ctx) error {

	return siw.Handler.CreateProject(c)
}

// GetProjectByID operation middleware
func (siw *ServerInterfaceWrapper) GetProjectByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "projectId", c.Params("projectId"), &projectId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	return siw.Handler.GetProjectByID(c, projectId)
}

// CreateStage operation middleware
func (siw *ServerInterfaceWrapper) CreateStage(c *fiber.Ctx) error {

	return siw.Handler.CreateStage(c)
}

// GetStageByID operation middleware
func (siw *ServerInterfaceWrapper) GetStageByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "stageId" -------------
	var stageId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "stageId", c.Params("stageId"), &stageId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter stageId: %w", err).Error())
	}

	return siw.Handler.GetStageByID(c, stageId)
}

// UpdateStage operation middleware
func (siw *ServerInterfaceWrapper) UpdateStage(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "stageId" -------------
	var stageId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "stageId", c.Params("stageId"), &stageId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter stageId: %w", err).Error())
	}

	return siw.Handler.UpdateStage(c, stageId)
}

// BatchCreateSubStages operation middleware
func (siw *ServerInterfaceWrapper) BatchCreateSubStages(c *fiber.Ctx) error {

	return siw.Handler.BatchCreateSubStages(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Post(options.BaseURL+"/customers", wrapper.CreateCustomer)

	router.Post(options.BaseURL+"/projectProgress", wrapper.CreateProjectProgress)

	router.Get(options.BaseURL+"/projectProgress/:progressId", wrapper.GetProjectProgressByID)

	router.Put(options.BaseURL+"/projectProgress/:progressId", wrapper.UpdateProjectProgress)

	router.Get(options.BaseURL+"/projects", wrapper.GetAllProjects)

	router.Post(options.BaseURL+"/projects", wrapper.CreateProject)

	router.Get(options.BaseURL+"/projects/:projectId", wrapper.GetProjectByID)

	router.Post(options.BaseURL+"/stages", wrapper.CreateStage)

	router.Get(options.BaseURL+"/stages/:stageId", wrapper.GetStageByID)

	router.Put(options.BaseURL+"/stages/:stageId", wrapper.UpdateStage)

	router.Post(options.BaseURL+"/subStages/batch", wrapper.BatchCreateSubStages)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+yZS2/jNhDHvwrB9tACauS0W2ChWx6LhYFuYWC3p0UOtDi2uZVIlRy5NQx/94IUJdsy",
	"48iJ/CjqUxzxMaPhj/8ZUkuaqrxQEiQamiypSWeQM/fzoTSoctD2d6FVARoFuJZUSWQpfsiZyOz/uCiA",
	"JtSgFnJKV1HdYQTaKBnuoYEh8Du0rROlc4Y0oZwh/IQiBxrtDhF8q29ZCh7qJlkOQZOFVt8gxWG3acqC",
	"H+bgqnmixtaOneSD1ioQP/f4QfGwn5/AGDYNt0E94a5xDX+VQgOnyVffLdowtJ72KeDnqApNYKUPX6Z0",
	"A5ve17CXVfFvO9JqqsGY1/D9+rD8/tyrdQxNvoeOntA3yDR+EdVc3d7OlOPPyKZwys3lDPaCLAeTalGg",
	"eEas/oPK89kvSD/xKTVrBUdIhCnoPqJjDgDnFWj2EE77SMiJsjNssULvRkMyUZrkTLKpkFPiXsZEpN7u",
	"JiJ+9de/7F+nPBFhkhNTjt0oMmaYzohdKxdtc2N9E5hZV76I9E9A8klJgcr6SR6ZmY0V05zcjYY0onPQ",
	"pnLq9mZwM7CvrgqQrBA0ob+4RxEtGM4cBXHjoCNEGReexrZdDvrgSGnKgCrFgMF7xRe1TIJ0A1lRZCJ1",
	"Q+NvPudXpYT99b2GCU3od/G61oh9oRE306+2kxjqEtwDUyhpKnR/Htweye72qtZtxO8VYso0BWMmZZYt",
	"bGDfDQa9OVLVCAEv7hknPuLkByHnLBOccIbsR+vCr6dwYSgRtGQZMaDnoAn4jlbw85zpRUMJYUTC3w32",
	"rk9cBBLtHtLaefk4wLWtnJi7oPntqI9aMnHF8FAM20JLNKRK8yCV8bLuNeQr6+IUAoR+BGyt3P1i+OgU",
	"VbMc0Anp1yUV1l+rsrTOeHQ9PW2DFm1E5oXct3ragXJwVig1oBYwD2L57vhM7PgjFZKJKiW/KCw/Au7S",
	"OF6Q4aMrDMsAan+4gmVXDP+3pPkK7srZHs4qaAiTBP4RBm2B2EUEzT7Bu8uyUd3tjUgIhNx0ZIOuC3Cm",
	"NVuEQvKbMEjUhLAsa+rri9v3bec61D7HrXnOVOvs21bX0uZ1pc32LnY1THXF0KWEOaR08RcXF55P9iF2",
	"IYXK5dYnrEkVvjCxaFUXGS8d2ao7puOIVjX3iSVrw+h2MF3DVa4OlSvj49kQFS/9fd9eoXLR7ixT9Q3i",
	"pYrUC1CdWaAqJy5Znvz1aIdTU61HJ2TmrMJ3MkbPega7ZEIDB69NzfOfYUzsLvefT6f3ttnn1HrMG/Jq",
	"p/NW840oeODqN+f24FCLCf/VJHw7SoSsPqdck/M2ro4zH7Lmy5O/hqmGVYrZOm6rlGWEwxwyVeQg0Zug",
	"ES11RhM6QyySOM5sv5kymLwfvB/ErBDx/Jaunlb/BgAA//8GN05bZyIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
