// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Customer defines model for Customer.
type Customer struct {
	ContactEmail  *string             `json:"contactEmail,omitempty"`
	ContactPerson *string             `json:"contactPerson,omitempty"`
	CreatedAt     *time.Time          `json:"createdAt,omitempty"`
	Id            *openapi_types.UUID `json:"id,omitempty"`
	Name          *string             `json:"name,omitempty"`
	ProjectId     *openapi_types.UUID `json:"projectId,omitempty"`
	UpdatedAt     *time.Time          `json:"updatedAt,omitempty"`
}

// CustomerWithProjectProgress defines model for CustomerWithProjectProgress.
type CustomerWithProjectProgress struct {
	ContactEmail    *string             `json:"contactEmail,omitempty"`
	ContactPerson   *string             `json:"contactPerson,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	Name            *string             `json:"name,omitempty"`
	ProjectId       *openapi_types.UUID `json:"projectId,omitempty"`
	ProjectProgress *[]ProjectProgress  `json:"projectProgress,omitempty"`
	UpdatedAt       *time.Time          `json:"updatedAt,omitempty"`
}

// Error defines model for Error.
type Error struct {
	ErrorCode string `json:"ErrorCode"`
	Message   string `json:"Message"`
	Error     string `json:"error"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	UpdatedAt *time.Time          `json:"updatedAt,omitempty"`
}

// ProjectProgress defines model for ProjectProgress.
type ProjectProgress struct {
	ContactEmail *string             `json:"contactEmail,omitempty"`
	CreatedAt    *time.Time          `json:"createdAt,omitempty"`
	CustomerName *string             `json:"customerName,omitempty"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Message      *string             `json:"message,omitempty"`
	Name         *string             `json:"name,omitempty"`
	ProjectId    *openapi_types.UUID `json:"projectId,omitempty"`
	StartTime    *time.Time          `json:"startTime,omitempty"`
	SubStageId   *openapi_types.UUID `json:"subStageId,omitempty"`
	UpdatedAt    *time.Time          `json:"updatedAt,omitempty"`
}

// Stage defines model for Stage.
type Stage struct {
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
	ProjectId   *openapi_types.UUID `json:"projectId,omitempty"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitempty"`
}

// StageWithSubStages defines model for StageWithSubStages.
type StageWithSubStages struct {
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Name        *string             `json:"name,omitempty"`
	ProjectId   *openapi_types.UUID `json:"projectId,omitempty"`
	SubStages   *[]SubStage         `json:"subStages,omitempty"`
	UpdatedAt   *time.Time          `json:"updatedAt,omitempty"`
}

// SubStage defines model for SubStage.
type SubStage struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Duration  *int                `json:"duration,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`
	Name      *string             `json:"name,omitempty"`
	StageId   *openapi_types.UUID `json:"stageId,omitempty"`
	StartTime *time.Time          `json:"startTime,omitempty"`
	UpdatedAt *time.Time          `json:"updatedAt,omitempty"`
}

// BatchCreateSubStagesJSONBody defines parameters for BatchCreateSubStages.
type BatchCreateSubStagesJSONBody = []SubStage

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = Customer

// CreateProjectProgressJSONRequestBody defines body for CreateProjectProgress for application/json ContentType.
type CreateProjectProgressJSONRequestBody = ProjectProgress

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = Project

// CreateStageJSONRequestBody defines body for CreateStage for application/json ContentType.
type CreateStageJSONRequestBody = Stage

// UpdateStageJSONRequestBody defines body for UpdateStage for application/json ContentType.
type UpdateStageJSONRequestBody = Stage

// BatchCreateSubStagesJSONRequestBody defines body for BatchCreateSubStages for application/json ContentType.
type BatchCreateSubStagesJSONRequestBody = BatchCreateSubStagesJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a new customer
	// (POST /customers)
	CreateCustomer(c *fiber.Ctx) error
	// Create a new project progress record
	// (POST /projectProgress)
	CreateProjectProgress(c *fiber.Ctx) error
	// Get project progress by ID
	// (GET /projectProgress/{progressId})
	GetProjectProgressByID(c *fiber.Ctx, progressId openapi_types.UUID) error
	// Update an existing project progress record
	// (PUT /projectProgress/{progressId})
	UpdateProjectProgress(c *fiber.Ctx, progressId openapi_types.UUID) error
	// Get all projects
	// (GET /projects)
	GetAllProjects(c *fiber.Ctx) error
	// Create a new project
	// (POST /projects)
	CreateProject(c *fiber.Ctx) error
	// Get a project by ID
	// (GET /projects/{projectId})
	GetProjectByID(c *fiber.Ctx, projectId openapi_types.UUID) error
	// Create a new stage
	// (POST /stages)
	CreateStage(c *fiber.Ctx) error
	// Get a stage by ID
	// (GET /stages/{stageId})
	GetStageByID(c *fiber.Ctx, stageId openapi_types.UUID) error
	// Update an existing stage
	// (PUT /stages/{stageId})
	UpdateStage(c *fiber.Ctx, stageId openapi_types.UUID) error
	// Batch create substages
	// (POST /subStages/batch)
	BatchCreateSubStages(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(c *fiber.Ctx) error {

	return siw.Handler.CreateCustomer(c)
}

// CreateProjectProgress operation middleware
func (siw *ServerInterfaceWrapper) CreateProjectProgress(c *fiber.Ctx) error {

	return siw.Handler.CreateProjectProgress(c)
}

// GetProjectProgressByID operation middleware
func (siw *ServerInterfaceWrapper) GetProjectProgressByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "progressId" -------------
	var progressId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "progressId", c.Params("progressId"), &progressId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter progressId: %w", err).Error())
	}

	return siw.Handler.GetProjectProgressByID(c, progressId)
}

// UpdateProjectProgress operation middleware
func (siw *ServerInterfaceWrapper) UpdateProjectProgress(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "progressId" -------------
	var progressId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "progressId", c.Params("progressId"), &progressId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter progressId: %w", err).Error())
	}

	return siw.Handler.UpdateProjectProgress(c, progressId)
}

// GetAllProjects operation middleware
func (siw *ServerInterfaceWrapper) GetAllProjects(c *fiber.Ctx) error {

	return siw.Handler.GetAllProjects(c)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(c *fiber.Ctx) error {

	return siw.Handler.CreateProject(c)
}

// GetProjectByID operation middleware
func (siw *ServerInterfaceWrapper) GetProjectByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "projectId", c.Params("projectId"), &projectId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter projectId: %w", err).Error())
	}

	return siw.Handler.GetProjectByID(c, projectId)
}

// CreateStage operation middleware
func (siw *ServerInterfaceWrapper) CreateStage(c *fiber.Ctx) error {

	return siw.Handler.CreateStage(c)
}

// GetStageByID operation middleware
func (siw *ServerInterfaceWrapper) GetStageByID(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "stageId" -------------
	var stageId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "stageId", c.Params("stageId"), &stageId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter stageId: %w", err).Error())
	}

	return siw.Handler.GetStageByID(c, stageId)
}

// UpdateStage operation middleware
func (siw *ServerInterfaceWrapper) UpdateStage(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "stageId" -------------
	var stageId openapi_types.UUID

	err = runtime.BindStyledParameter("simple", false, "stageId", c.Params("stageId"), &stageId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter stageId: %w", err).Error())
	}

	return siw.Handler.UpdateStage(c, stageId)
}

// BatchCreateSubStages operation middleware
func (siw *ServerInterfaceWrapper) BatchCreateSubStages(c *fiber.Ctx) error {

	return siw.Handler.BatchCreateSubStages(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(m)
	}

	router.Post(options.BaseURL+"/customers", wrapper.CreateCustomer)

	router.Post(options.BaseURL+"/projectProgress", wrapper.CreateProjectProgress)

	router.Get(options.BaseURL+"/projectProgress/:progressId", wrapper.GetProjectProgressByID)

	router.Put(options.BaseURL+"/projectProgress/:progressId", wrapper.UpdateProjectProgress)

	router.Get(options.BaseURL+"/projects", wrapper.GetAllProjects)

	router.Post(options.BaseURL+"/projects", wrapper.CreateProject)

	router.Get(options.BaseURL+"/projects/:projectId", wrapper.GetProjectByID)

	router.Post(options.BaseURL+"/stages", wrapper.CreateStage)

	router.Get(options.BaseURL+"/stages/:stageId", wrapper.GetStageByID)

	router.Put(options.BaseURL+"/stages/:stageId", wrapper.UpdateStage)

	router.Post(options.BaseURL+"/subStages/batch", wrapper.BatchCreateSubStages)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZXY+jNhT9K5bbh1aiQ6bdSqu8zcdqFalbRdqt+rCaBwduEm/BpvYl2yjKf69sDCTg",
	"ycAsyWTaPA0Dxr4cn3vu8c2GRjLNpACBmo43VEdLSJm9vMs1yhSUuc6UzEAhB/skkgJZhO9SxhPzP64z",
	"oGOqUXGxoNugHDAFpaXwj1DAEOIbNE/nUqUM6ZjGDOEn5CnQoP0Kj/fG5jmPfcMES8G7ZKbkF4hw0m2a",
	"PIv7Bbit7siZWcdMUkL4J8fltFh+quRCgdb/T1SzNggcIbUX3yuY0zH9LqwZGTo6hk3warCZUmw92Ia9",
	"U0p6CG9v38nYD8EH0Jot/M+gnLC9uIK/c64gpuPPbliws1A97YMnToeHh0SnZ8AgwA+QHf2/PHLp+ftj",
	"n9YRmvQAAQZKHI1M4SdezNXt63Q++4hsAacUPLvgIKyMQUeKZ8gfkbpXWA0sOKYUfHQ7o/+DSOndb+uk",
	"7SUaRxP1aoFB0M4Va0DNBcIC1BBY6x4J+wxJGABOc4uLuTQz7DGP3kwnZC4VSZlgCy4WxH6MDkgpszog",
	"jkv1lflrFT8gTMRE5zP7FpkxjJbE7JVFW1+Z2DgmJpRPPPoLkHyQgqM0cZJ7ppczyVRMbqYTGtAVKF0E",
	"dX01uhqZT5cZCJZxOqa/2FsBzRguLQvCKkDLEKktPNXaZjvonWVKZYmL6g0ab2W8LssTCPsiy7KER/bV",
	"8ItzagXXn8qEavrtvj9AlYO9oTMpdEHdn0fXR1p3f1fLZ8TlCtF5FIHW8zxJbIq+GY0GC6SwX54obllM",
	"HOLkBy5WLOExiRmyH00Iv54ihIlAUIIlRINagSLgBhrJS1Om1hVLCCMCvla0t2NCj/M9xLSmHzoO4Vq2",
	"+rS88y6/j/q0IRMXGvalYVNoiYJIqtjLynBTjprEWxPiAjwMfQ/Y2Lnb9eTeKqpiKaAV0s8byk28RmVp",
	"WfFoPT1tEi3YQeaJ2rd9aJGyH/INF7Ar/1100necN2Wxk9tpm8DaY3VMmMop6B0T4TyTv2L7k0oBKg6r",
	"RjaRrxyXVfEuK7Ir0DVWNufeHJ/wZbBCIpnLXMRnlWrvAdsZNluTyb3d1tyTPn9YE9YW+FeTPUNLunOl",
	"Hkk/Ib2qaM6TZwVpCBME/uEajentIuz6kIjfJMm0HPaNlOjTxGuf89qQ/MY1EjknLEmqM8PZ5X0zuA5+",
	"7rg+7oX826G0uti159m1/Sy2vqxownSxZX3smGvtnHk96e9iLv6k1qmqVDhjYqhV+8dDslX0zY4jWq7p",
	"d1rJ2ll0H0z74CJXfeVKOzwrRoUb18M8KFQW7c4yVXZFz1WkniDVCwtUEcQ5y5Nr+XY4NZV6dELOvKjw",
	"nYyjL3oGO2eGeg5eu5pXNnFC+4PF4+X01jx2NbVq/DyfXt/4w9rwNXeAgBqcKPtO3ppMuCh+IroU5326",
	"Wp45yOreXTFb8VqhmI3jtoxYQmJYQSKzFAS6JWhAc5XQMV0iZuMwTMy4pdQ4fjt6OwpZxsPVNd0+bP8N",
	"AAD//608jA1HJgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
